<?php

function clock_angle_menu() {
    $items = array();
    $items['clock_angle'] = array(
            'title' => 'Clock Angle Calculator',
            'page callback' => 'drupal_get_form',
            'page arguments' => array(clock_angle_form),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    $items['clock_angle_success_page'] = array(
            'title' => 'Success',
            'page callback' => 'clock_angle_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );

    return $items;
} //end clock_angle_menu()


function clock_angle_form() {
    $form['time'] = array(
            '#title' => 'Time',
            '#type' => 'textfield',
            '#description' => t('Please enter the time (format: hh:mm) to calculate the clock angle.'),
        );
    $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Calculate',
        );

    return $form;
} //end clock_angle_form()


function clock_angle_form_submit($form, &$form_state) {
    $time = $form_state['values']['time'];
    $pattern = "/^[0-2]?\d:[0-5]\d$/";
    $correct_format = preg_match($pattern, $time);
    $time_elements = preg_split('/:/', $time);
    if ($correct_format == 1) { //only do this check if we have numbers, a colon, and numbers
        if (($time_elements[0] >= 24) || ($time_elements[1] >= 60)) { //still not a valid time
            $correct_format = 0;
        }
    }

    if ($correct_format) {
        $_SESSION['angle'] = angle_calculator($time_elements[0], $time_elements[1]);
        $_SESSION['time'] = $time;
        $form_state['redirect'] = 'clock_angle_success_page';
    }
    else { //User didn't enter a time in the correct format
        drupal_set_message("Incorrect time, please enter a valid time in the format hh:mm");
    }
} //end clock_angle_form_submit()


function clock_angle_success() {
    $time = $_SESSION['time'];
    $angle = $_SESSION['angle'];
    return "The angle of the time $time is $angle degrees.";
} //end clock_angle_success()


function angle_calculator($hour, $minute) {
    $hour_additional = $minute / 60;    //hourhand is exactly on the hour only when $minute == 0
    $hour += $hour_additional;
    if ($hour > 12) {$hour -= 12;}      //convert military time to standard time
    if ($hour == 0) {$hour = 12;}       //hour 0 in military time is 12 in the morning
    $hour *= 5;                         //put hour on the minutes plane

    $angle = $hour - $minute;
    if ($angle < 0) {$angle *= -1;}
    $angle *= 6;                        //for every minute difference the hour and minute hands are, there is a 6 degree difference (360 degree circle / 60 minutes in that circle)
    if ($angle == 360) {$angle = 0;}
    elseif ($angle > 180) {$angle -= 180;} // we are looking for the smallest angle
    return $angle;
} //end angle_calculator()
