<?php

function sum_menu() {
    $items = array();
    $items['sum'] = array(
            'title' => 'Calculate Sum',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('sum_form'),
        );
    $items['success'] = array(
            'title' => 'Success',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'sum_success',
        );
    return $items;
} //end sum_menu()

function sum_form() {
    $form = array();
    $form['left_number'] = array(
            '#title' => 'Left Number',
            '#type' => 'textfield',
            '#description' => t('Please enter your starting number.'),
        );

    $form['right_number'] = array(
            '#title' => 'Right Number',
            '#type' => 'textfield',
            '#description' => t('Please enter a number to add to the starting number.'),
        );

    $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Calculate Sum', //the text that is printed on the button
        );

    return $form;
} //end sum_form()


function sum_form_submit($form, &$form_state) {
    //Parameter, $form: was created and returned from the function above, sum_form()
    //Parameter, &$form_state: after the form is submitted, all of the user supplied details is contained in the array &$form_state

    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum_output'] = $sum; //the $_SESSION array is special to php. The name 'sum_output' is just a name created, that could be any name.
    $form_state['redirect'] = 'success';
} //end sum_form_submit()

function sum_success() {
    $answer = $_SESSION['sum_output'];
    return "Your sum is $answer";
}
