<?php

function title_case_menu() {
    $items = array();
    $items['title_case'] = array(
        'title' => "Title Case",
        'page_callback' => "drupal_get_form",
        'access_callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'page arguments' => array('title_case_form'),
    );

    return $items;

} //end title_case_menu()


function title_case_form() {
    $form = array();

    $form['sentence'] = array(
        '#title' => 'Sentence',
        '#type' => 'textfield',
        '#description' => t('Please enter your sentence to be changed to title case.'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
} //end title_case_page()


function title_case_form_submit($form, &$form_state) {
    $_SESSION['sentence'] = convert_to_title_case($form_state['values']['sentence']);
    $form_state['redirect'] = 'title_case_final_page';
} //end title_case_form_submit()


function convert_to_title_case($sentence) {
    return $sentence;
} //end convert_to_title_case()


function title_case_final_page() {
    return $_SESSION['sentence'];
} //end title_case_final_page()
