<?php

function title_case_menu() {
    $items = array();
    $items['title_case'] = array(
        'title' => "Title Case",
        'page callback' => "drupal_get_form",
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'page arguments' => array('title_case_form'),
    );

    $items['title_case_final'] = array(
        'title' => 'Title Case',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'title_case_final_page',
    );

    return $items;

} //end title_case_menu()


function title_case_form() {
    $form = array();

    $form['sentence'] = array(
        '#title' => 'Sentence',
        '#type' => 'textfield',
        '#description' => t('Please enter your sentence to be changed to title case.'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
} //end title_case_page()


function title_case_form_submit($form, &$form_state) {
    $_SESSION['sentence'] = convert_to_title_case($form_state['values']['sentence']);
    $form_state['redirect'] = 'title_case_final';
} //end title_case_form_submit()


function convert_to_title_case($sentence) {
    $words_not_to_capitalize_array = ["a", "an", "the", "and", "or", "for", "nor", "on", "at", "to", "from", "by", "but", "yet", "so", "as", "from", "in", "into", "than", "through", "throughout", "up", "vs", "vs.", "when", "with", "within", "without", "of"];
    $sentence_array = explode(" ", $sentence);
    $array_length = count($sentence_array);
    $counter = 1; //First and last word are always capitalized. We are going to test if it is the first word using $counter or the last word using $counter and $array_length

    foreach ($sentence_array as &$word) {
        $word = strtolower($word);
        $found = 0;
        if (($counter != 1) && ($counter != $array_length)) {
            foreach ($words_not_to_capitalize_array as $non_word) {
                if ($word == $non_word) {
                    $found = 1;
                    break 1;
                }
            }
        }
        if ($found == 0) { //$found will equal 0 if we did not find a non word, if it is the first word, or if it is the last word
            $word = ucfirst($word);
        }
        $counter++; //we are moving on to the next word
    }

    $sentence = implode(" ", $sentence_array);

    return $sentence;
} //end convert_to_title_case()


function title_case_final_page() {
    $sentence = $_SESSION['sentence'];
    return "<p>Your sentence in title case:</p><p align=\"center\">$sentence</p>";
} //end title_case_final_page()
